linters:
  enable:
  - goconst
  - gocyclo
  - gosec
  - stylecheck
  - unconvert
  disable:
  - errcheck
  fast: false

linters-settings:
  goconst:
    min-occurrences: 4

issues:
  exclude-rules:
  - linters: [gosec]
    path: processor.go
    text: "G404: Use of weak random number generator"
