version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3

jobs:

  unit-test:
    docker:
    - image: golang:1.18

    steps:
    - checkout
    - run: 
        name: Unit test
        command: |
          go test -v -mod=readonly -race -count=1 -cover -coverprofile=profile.cov ./...
    - codecov/upload:
        file: profile.cov

workflows:
  version: 2
  build-workflow:
    jobs:
    - unit-test
